endconditions:
  # Name of the leading team
  FacilityForces:
    ##Condition name: Literally up to you, can be used as an identifier if you want
    ##The ONLY rule for this is to NOT have two with the same name that are under the same leading team.
    #Append "+science" or "+classd" to the name to check if at least one person has escaped from that team
    #Append "-science" or "-classd" to the name to check if nobody has escaped from that team
    #Note that this can create situations where the round will not end if there is one person alive. Make sure you cover all situations.
    - Default +science:
        #Who wins together, using ClassNames from #resources in the EXILED discord
        - NtfCaptain
        - NtfSergeant
        - NtfPrivate
        - NtfSpecialist
        - FacilityGuard
        - Scientist
  ChaosInsurgency:
    - Default +classd:
        - ChaosRepressor
        - ChaosMarauder
        - ChaosRifleman
        - ChaosConscript
        - ClassD
    - Default2 +classd:
        - ChaosRepressor
        - ChaosMarauder
        - ChaosRifleman
        - ChaosConscript
        - Scp173
        - Scp106
        - Scp049
        - Scp079
        - Scp096
        - Scp0492
        - Scp93953
        - Scp93989
        - SerpentsHand
        - Scp035
  Anomalies:
    - Default time:
        - Scp173
        - Scp106
        - Scp049
        - Scp079
        - Scp096
        - Scp0492
        - Scp93953
        - Scp93989
        - SerpentsHand
        - Scp035
        - ChaosRepressor
        - ChaosMarauder
        - ChaosRifleman
        - ChaosConscript
  Draw:
    - Default time:
        - ChaosRepressor
        - ChaosMarauder
        - ChaosRifleman
        - ChaosConscript
        - Scp173
        - Scp106
        - Scp049
        - Scp079
        - Scp096
        - Scp0492
        - Scp93953
        - Scp93989
        - SerpentsHand
        - Scp035
    - Default 2:
        - ClassD
        - ChaosRepressor
        - ChaosMarauder
        - ChaosRifleman
        - ChaosConscript
    - Default 3:
        - NtfCaptain
        - NtfSergeant
        - NtfPrivate
        - NtfSpecialist
        - FacilityGuard
        - Scientist