name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nuget
        uses: iRebbok/setup-nuget@master

      - name: Restore Packages
        run: nuget restore EndConditions.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download references
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://www.exiled.host/build_deps/References.zip'
          file-name: 'References.zip'

      - name: Download 7zip
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://www.exiled.host/7za.exe'
          file-name: '7zip.exe'

      - name: Extract Refs
        run: ./7zip.exe e References.zip -oEndConditions/lib/ -r -y

      - name: Download Serpents Hand
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://github.com/Exiled-Team/SerpentsHand/releases/latest/download/SerpentsHand.dll'
          file-name: 'SerpentsHand.dll'
          location: EndConditions/lib/

      - name: Build
        run: msbuild EndConditions.sln -p:Configuration=release

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: Plugin DLL
          path: EndConditions\bin\Release\EndConditions*.dll
